// AUTOMATICALLY GENERATED FILE.  DO NOT EDIT
// Created by gen_expressions.py script
static std::map<std::string, std::string> gFunctionRename = {
    {"agate", "agate"},
    {"blotches", "blotches"},
    {"clouds", "clouds"},
    {"flecks", "flecks"},
    {"grain", "grain"},
    {"noise", "noise"},
    {"plasma", "plasma"},
    {"snoise", "snoise"},
    {"splasma", "splasma"},
    {"spots", "spots"},
    {"turbulence", "turbulence"},
    {"velvet", "velvet"},
    {"vnoise", "vnoise"},
    {"vplasma", "vplasma"},
    {"vsnoise", "vsnoise"},
    {"vsplasma", "vsplasma"},
    {"vturbulence", "vturbulence"},
    {"wood", "wood"},
    {"alpha", "alpha"},
    {"blue-from-hsl", "blue_from_hsl"},
    {"gradient", "gradient"},
    {"green-from-hsl", "green_from_hsl"},
    {"height", "height"},
    {"height-normal", "height_normal"},
    {"hsl-from-rgb", "hsl_from_rgb"},
    {"hue-from-rgb", "hue_from_rgb"},
    {"length", "vlength"},
    {"lightness-from-rgb", "lightness_from_rgb"},
    {"max-component", "max_component"},
    {"min-component", "min_component"},
    {"normalize", "vnormalize"},
    {"polar", "polar"},
    {"radius", "radius"},
    {"red-from-hsl", "red_from_hsl"},
    {"rgb-from-hsl", "rgb_from_hsl"},
    {"saturation-from-rgb", "saturation_from_rgb"},
    {"sigmoid", "sigmoid"},
    {"square", "square"},
    {"t", "t"},
    {"theta", "theta"},
    {"triangle-wave", "triangle_wave"},
    {"vabs", "vabs"},
    {"vcos", "vcos"},
    {"vfloor", "vfloor"},
    {"vfrac", "vfrac"},
    {"vround", "vround"},
    {"vsin", "vsin"},
    {"vsqrt", "vsqrt"},
    {"x", "x"},
    {"y", "y"},
    {"z", "z"},
    {"adjust-hsl", "adjust_hsl"},
    {"adjust-hue", "adjust_hue"},
    {"average", "average"},
    {"checker", "checker"},
    {"cross3", "cross3"},
    {"dot", "vdot"},
    {"offset", "offset"},
    {"rotate", "rotate"},
    {"scale", "scale"},
    {"turbulate", "turbulate"},
    {"v*", "vmul"},
    {"v+", "vadd"},
    {"v-", "vsub"},
    {"vconcat", "vconcat"},
    {"vdivide", "vdivide"},
    {"vmax", "vmax"},
    {"vmin", "vmin"},
    {"vmod", "vmod"},
    {"vpow", "vpow"},
    {"clamp", "vclamp"},
    {"lerp", "lerp"},
    {"vif", "vif"},
};

static std::set<std::string> gAddPos = {
    "agate",
    "blotches",
    "clouds",
    "flecks",
    "grain",
    "noise",
    "plasma",
    "snoise",
    "splasma",
    "spots",
    "turbulence",
    "velvet",
    "vnoise",
    "vplasma",
    "vsnoise",
    "vsplasma",
    "vturbulence",
    "wood",
    "gradient",
    "checker",
    "offset",
    "rotate",
    "scale",
    "turbulate",
};

static std::set<std::string> gModPos = {
    "gradient",
    "offset",
    "rotate",
    "scale",
    "turbulate",
};

static std::set<std::string> gTermFns = {
    "agate",
    "blotches",
    "clouds",
    "flecks",
    "grain",
    "noise",
    "plasma",
    "snoise",
    "splasma",
    "spots",
    "turbulence",
    "velvet",
    "vnoise",
    "vplasma",
    "vsnoise",
    "vsplasma",
    "vturbulence",
    "wood",
};

